use std::str::FromStr;
use openssl::ssl::{SslStream};
use std::io::{Write, Read};
use crate::irc::core::Irc;
use crate::commands::Command;


pub enum Stream<T: Write + Read> {
    Tcp(T),
    Tls(SslStream<T>)
}


#[derive(Debug)]
pub enum IrcErrors {
    TcpStreamConnect,
    SslConnectorBuild,
    SslStreamConnect,
    StreamError,
    NotMaster,
    UnknownFunction,
    Unknown
}

#[derive(Debug)]
pub enum CommandErrors {
    Unknown
}

pub type IrcResult      = Result<Irc, IrcErrors>;
pub type CommandResult  = Result<Command, IrcErrors>;
pub type VoidResult     = Result<(), IrcErrors>;


#[allow(non_camel_case_types)]
#[derive(Debug, PartialEq)]
pub enum StatusCode {

    // for some obscure ircd
    UNKNOWN,

    // Events
    PASS,
    NICK,
    USER,
    OPER,
    MODE,
    SERVICE,
    QUIT,
    SQUIT,
    JOIN,
    PART,
    TOPIC,
    NAMES,
    LIST,
    INVITE,
    KICK,
    PRIVMSG,
    NOTICE,
    AUTH,
    MOTD,
    LUSERS,
    VERSION,
    STATS,
    LINKS,
    TIME,
    CONNECT,
    TRACE,
    ADMIN,
    INFO,
    SERVLIST,
    SQUERY,
    WHO,
    WHOIS,
    WHOWAS,
    KILL,
    PING,
    PONG,
    ERROR,
    AWAY,
    REHASH,
    DIE,
    RESTART,
    SUMMON,
    USERS,
    WALLOPS,
    USERHOST,
    ISON,

    //

    RPL_WELCOME,
    RPL_YOURHOST,
    RPL_CREATED,
    RPL_MYINFO,
    RPL_BOUNCE,


    // Replies generated in the response to commands are found in the range from 200 to 399.

    RPL_TRACELINK,
    RPL_TRACECONNECTING,
    RPL_TRACEHANDSHAKE,
    RPL_TRACEUNKNOWN,
    RPL_TRACEOPERATOR,
    RPL_TRACEUSER,
    RPL_TRACESERVER,
    RPL_TRACESERVICE,
    RPL_TRACENEWTYPE,
    RPL_TRACECLASS,
    RPL_TRACERECONNECT,
    RPL_STATSLINKINFO,
    RPL_STATSCOMMANDS,
    RPL_ENDOFSTATS,
    RPL_UMODEIS,
    RPL_SERVLIST,
    RPL_SERVLISTEND,
    RPL_STATSUPTIME,
    RPL_STATSOLINE,
    RPL_LUSERCLIENT,
    RPL_LUSEROP,
    RPL_LUSERUNKNOWN,
    RPL_LUSERCHANNELS,
    RPL_LUSERME,
    RPL_ADMINME,
    RPL_ADMINLOC1,
    RPL_ADMINLOC2,
    RPL_ADMINEMAIL,
    RPL_TRACELOG,
    RPL_TRACEEND,
    RPL_TRYAGAIN,
    RPL_AWAY,
    RPL_USERHOST,
    RPL_ISON,
    RPL_UNAWAY,
    RPL_NOWAWAY,
    RPL_WHOISUSER,
    RPL_WHOISSERVER,
    RPL_WHOISOPERATOR,
    RPL_WHOWASUSER,
    RPL_ENDOFWHO,
    RPL_WHOISIDLE,
    RPL_ENDOFWHOIS,
    RPL_WHOISCHANNELS,
    RPL_LISTSTART,
    RPL_LIST,
    RPL_LISTEND,
    RPL_CHANNELMODEIS,
    RPL_UNIQOPIS,
    RPL_NOTOPIC,
    RPL_TOPIC,
    RPL_INVITING,
    RPL_SUMMONING,
    RPL_INVITELIST,
    RPL_ENDOFINVITELIST,
    RPL_EXCEPTLIST,
    RPL_ENDOFEXCEPTLIST,
    RPL_VERSION,
    RPL_WHOREPLY,
    RPL_NAMREPLY,
    RPL_LINKS,
    RPL_ENDOFLINKS,
    RPL_ENDOFNAMES,
    RPL_BANLIST,
    RPL_ENDOFBANLIST,
    RPL_ENDOFWHOWAS,
    RPL_INFO,
    RPL_MOTD,
    RPL_ENDOFINFO,
    RPL_MOTDSTART,
    RPL_ENDOFMOTD,
    RPL_YOUREOPER,
    RPL_REHASHING,
    RPL_YOURESERVICE,
    RPL_TIME,
    RPL_USERSSTART,
    RPL_USERS,
    RPL_ENDOFUSERS,
    RPL_NOUSERS,

    // Error replies are found in the range from 400 to 599.

    ERR_NOSUCHNICK,
    ERR_NOSUCHSERVER,
    ERR_NOSUCHCHANNEL,
    ERR_CANNOTSENDTOCHAN,
    ERR_TOOMANYCHANNELS,
    ERR_WASNOSUCHNICK,
    ERR_TOOMANYTARGETS,
    ERR_NOSUCHSERVICE,
    ERR_NOORIGIN,
    ERR_NORECIPIENT,
    ERR_NOTEXTTOSEND,
    ERR_NOTOPLEVEL,
    ERR_WILDTOPLEVEL,
    ERR_BADMASK,
    ERR_UNKNOWNCOMMAND,
    ERR_NOMOTD,
    ERR_NOADMININFO,
    ERR_FILEERROR,
    ERR_NONICKNAMEGIVEN,
    ERR_ERRONEUSNICKNAME,
    ERR_NICKNAMEINUSE,
    ERR_NICKCOLLISION,
    ERR_UNAVAILRESOURCE,
    ERR_USERNOTINCHANNEL,
    ERR_NOTONCHANNEL,
    ERR_USERONCHANNEL,
    ERR_NOLOGIN,
    ERR_SUMMONDISABLED,
    ERR_USERSDISABLED,
    ERR_NOTREGISTERED,
    ERR_NEEDMOREPARAMS,
    ERR_ALREADYREGISTRED,
    ERR_NOPERMFORHOST,
    ERR_PASSWDMISMATCH,
    ERR_YOUREBANNEDCREEP,
    ERR_YOUWILLBEBANNED,
    ERR_KEYSET,
    ERR_CHANNELISFULL,
    ERR_UNKNOWNMODE,
    ERR_INVITEONLYCHAN,
    ERR_BANNEDFROMCHAN,
    ERR_BADCHANNELKEY,
    ERR_BADCHANMASK,
    ERR_NOCHANMODES,
    ERR_BANLISTFULL,
    ERR_NOPRIVILEGES,
    ERR_CHANOPRIVSNEEDED,
    ERR_CANTKILLSERVER,
    ERR_RESTRICTED,
    ERR_UNIQOPPRIVSNEEDED,
    ERR_NOOPERHOST,
    ERR_UMODEUNKNOWNFLAG,
    ERR_USERSDONTMATCH,
}

impl FromStr for StatusCode {
    type Err = &'static str;

    fn from_str(string: &str) -> Result<StatusCode, &'static str> {
        match string {
            "PASS" => Ok(StatusCode::PASS),
            "NICK" => Ok(StatusCode::NICK),
            "USER" => Ok(StatusCode::USER),
            "OPER" => Ok(StatusCode::OPER),
            "MODE" => Ok(StatusCode::MODE),
            "SERVICE" => Ok(StatusCode::SERVICE),
            "QUIT" => Ok(StatusCode::QUIT),
            "SQUIT" => Ok(StatusCode::SQUIT),
            "JOIN" => Ok(StatusCode::JOIN),
            "PART" => Ok(StatusCode::PART),
            "TOPIC" => Ok(StatusCode::TOPIC),
            "NAMES" => Ok(StatusCode::NAMES),
            "LIST" => Ok(StatusCode::LIST),
            "INVITE" => Ok(StatusCode::INVITE),
            "KICK" => Ok(StatusCode::KICK),
            "PRIVMSG" => Ok(StatusCode::PRIVMSG),
            "NOTICE" => Ok(StatusCode::NOTICE),
            "AUTH" => Ok(StatusCode::AUTH),
            "MOTD" => Ok(StatusCode::MOTD),
            "LUSERS" => Ok(StatusCode::LUSERS),
            "VERSION" => Ok(StatusCode::VERSION),
            "STATS" => Ok(StatusCode::STATS),
            "LINKS" => Ok(StatusCode::LINKS),
            "TIME" => Ok(StatusCode::TIME),
            "CONNECT" => Ok(StatusCode::CONNECT),
            "TRACE" => Ok(StatusCode::TRACE),
            "ADMIN" => Ok(StatusCode::ADMIN),
            "INFO" => Ok(StatusCode::INFO),
            "SERVLIST" => Ok(StatusCode::SERVLIST),
            "SQUERY" => Ok(StatusCode::SQUERY),
            "WHO" => Ok(StatusCode::WHO),
            "WHOIS" => Ok(StatusCode::WHOIS),
            "WHOWAS" => Ok(StatusCode::WHOWAS),
            "KILL" => Ok(StatusCode::KILL),
            "PING" => Ok(StatusCode::PING),
            "PONG" => Ok(StatusCode::PONG),
            "ERROR" => Ok(StatusCode::ERROR),
            "AWAY" => Ok(StatusCode::AWAY),
            "REHASH" => Ok(StatusCode::REHASH),
            "DIE" => Ok(StatusCode::DIE),
            "RESTART" => Ok(StatusCode::RESTART),
            "SUMMON" => Ok(StatusCode::SUMMON),
            "USERS" => Ok(StatusCode::USERS),
            "WALLOPS" => Ok(StatusCode::WALLOPS),
            "USERHOST" => Ok(StatusCode::USERHOST),
            "ISON" => Ok(StatusCode::ISON),
            "001" => Ok(StatusCode::RPL_WELCOME),
            "002" => Ok(StatusCode::RPL_YOURHOST),
            "003" => Ok(StatusCode::RPL_CREATED),
            "004" => Ok(StatusCode::RPL_MYINFO),
            "005" => Ok(StatusCode::RPL_BOUNCE),
            "200" => Ok(StatusCode::RPL_TRACELINK),
            "201" => Ok(StatusCode::RPL_TRACECONNECTING),
            "202" => Ok(StatusCode::RPL_TRACEHANDSHAKE),
            "203" => Ok(StatusCode::RPL_TRACEUNKNOWN),
            "204" => Ok(StatusCode::RPL_TRACEOPERATOR),
            "205" => Ok(StatusCode::RPL_TRACEUSER),
            "206" => Ok(StatusCode::RPL_TRACESERVER),
            "207" => Ok(StatusCode::RPL_TRACESERVICE),
            "208" => Ok(StatusCode::RPL_TRACENEWTYPE),
            "209" => Ok(StatusCode::RPL_TRACECLASS),
            "210" => Ok(StatusCode::RPL_TRACERECONNECT),
            "211" => Ok(StatusCode::RPL_STATSLINKINFO),
            "212" => Ok(StatusCode::RPL_STATSCOMMANDS),
            "219" => Ok(StatusCode::RPL_ENDOFSTATS),
            "221" => Ok(StatusCode::RPL_UMODEIS),
            "234" => Ok(StatusCode::RPL_SERVLIST),
            "235" => Ok(StatusCode::RPL_SERVLISTEND),
            "242" => Ok(StatusCode::RPL_STATSUPTIME),
            "243" => Ok(StatusCode::RPL_STATSOLINE),
            "251" => Ok(StatusCode::RPL_LUSERCLIENT),
            "252" => Ok(StatusCode::RPL_LUSEROP),
            "253" => Ok(StatusCode::RPL_LUSERUNKNOWN),
            "254" => Ok(StatusCode::RPL_LUSERCHANNELS),
            "255" => Ok(StatusCode::RPL_LUSERME),
            "256" => Ok(StatusCode::RPL_ADMINME),
            "257" => Ok(StatusCode::RPL_ADMINLOC1),
            "258" => Ok(StatusCode::RPL_ADMINLOC2),
            "259" => Ok(StatusCode::RPL_ADMINEMAIL),
            "261" => Ok(StatusCode::RPL_TRACELOG),
            "262" => Ok(StatusCode::RPL_TRACEEND),
            "263" => Ok(StatusCode::RPL_TRYAGAIN),
            "301" => Ok(StatusCode::RPL_AWAY),
            "302" => Ok(StatusCode::RPL_USERHOST),
            "303" => Ok(StatusCode::RPL_ISON),
            "305" => Ok(StatusCode::RPL_UNAWAY),
            "306" => Ok(StatusCode::RPL_NOWAWAY),
            "311" => Ok(StatusCode::RPL_WHOISUSER),
            "312" => Ok(StatusCode::RPL_WHOISSERVER),
            "313" => Ok(StatusCode::RPL_WHOISOPERATOR),
            "314" => Ok(StatusCode::RPL_WHOWASUSER),
            "315" => Ok(StatusCode::RPL_ENDOFWHO),
            "317" => Ok(StatusCode::RPL_WHOISIDLE),
            "318" => Ok(StatusCode::RPL_ENDOFWHOIS),
            "319" => Ok(StatusCode::RPL_WHOISCHANNELS),
            "321" => Ok(StatusCode::RPL_LISTSTART),
            "322" => Ok(StatusCode::RPL_LIST),
            "323" => Ok(StatusCode::RPL_LISTEND),
            "324" => Ok(StatusCode::RPL_CHANNELMODEIS),
            "325" => Ok(StatusCode::RPL_UNIQOPIS),
            "331" => Ok(StatusCode::RPL_NOTOPIC),
            "332" => Ok(StatusCode::RPL_TOPIC),
            "341" => Ok(StatusCode::RPL_INVITING),
            "342" => Ok(StatusCode::RPL_SUMMONING),
            "346" => Ok(StatusCode::RPL_INVITELIST),
            "347" => Ok(StatusCode::RPL_ENDOFINVITELIST),
            "348" => Ok(StatusCode::RPL_EXCEPTLIST),
            "349" => Ok(StatusCode::RPL_ENDOFEXCEPTLIST),
            "351" => Ok(StatusCode::RPL_VERSION),
            "352" => Ok(StatusCode::RPL_WHOREPLY),
            "353" => Ok(StatusCode::RPL_NAMREPLY),
            "364" => Ok(StatusCode::RPL_LINKS),
            "365" => Ok(StatusCode::RPL_ENDOFLINKS),
            "366" => Ok(StatusCode::RPL_ENDOFNAMES),
            "367" => Ok(StatusCode::RPL_BANLIST),
            "368" => Ok(StatusCode::RPL_ENDOFBANLIST),
            "369" => Ok(StatusCode::RPL_ENDOFWHOWAS),
            "371" => Ok(StatusCode::RPL_INFO),
            "372" => Ok(StatusCode::RPL_MOTD),
            "374" => Ok(StatusCode::RPL_ENDOFINFO),
            "375" => Ok(StatusCode::RPL_MOTDSTART),
            "376" => Ok(StatusCode::RPL_ENDOFMOTD),
            "381" => Ok(StatusCode::RPL_YOUREOPER),
            "382" => Ok(StatusCode::RPL_REHASHING),
            "383" => Ok(StatusCode::RPL_YOURESERVICE),
            "391" => Ok(StatusCode::RPL_TIME),
            "392" => Ok(StatusCode::RPL_USERSSTART),
            "393" => Ok(StatusCode::RPL_USERS),
            "394" => Ok(StatusCode::RPL_ENDOFUSERS),
            "395" => Ok(StatusCode::RPL_NOUSERS),
            "401" => Ok(StatusCode::ERR_NOSUCHNICK),
            "402" => Ok(StatusCode::ERR_NOSUCHSERVER),
            "403" => Ok(StatusCode::ERR_NOSUCHCHANNEL),
            "404" => Ok(StatusCode::ERR_CANNOTSENDTOCHAN),
            "405" => Ok(StatusCode::ERR_TOOMANYCHANNELS),
            "406" => Ok(StatusCode::ERR_WASNOSUCHNICK),
            "407" => Ok(StatusCode::ERR_TOOMANYTARGETS),
            "408" => Ok(StatusCode::ERR_NOSUCHSERVICE),
            "409" => Ok(StatusCode::ERR_NOORIGIN),
            "411" => Ok(StatusCode::ERR_NORECIPIENT),
            "412" => Ok(StatusCode::ERR_NOTEXTTOSEND),
            "413" => Ok(StatusCode::ERR_NOTOPLEVEL),
            "414" => Ok(StatusCode::ERR_WILDTOPLEVEL),
            "415" => Ok(StatusCode::ERR_BADMASK),
            "421" => Ok(StatusCode::ERR_UNKNOWNCOMMAND),
            "422" => Ok(StatusCode::ERR_NOMOTD),
            "423" => Ok(StatusCode::ERR_NOADMININFO),
            "424" => Ok(StatusCode::ERR_FILEERROR),
            "431" => Ok(StatusCode::ERR_NONICKNAMEGIVEN),
            "432" => Ok(StatusCode::ERR_ERRONEUSNICKNAME),
            "433" => Ok(StatusCode::ERR_NICKNAMEINUSE),
            "436" => Ok(StatusCode::ERR_NICKCOLLISION),
            "437" => Ok(StatusCode::ERR_UNAVAILRESOURCE),
            "441" => Ok(StatusCode::ERR_USERNOTINCHANNEL),
            "442" => Ok(StatusCode::ERR_NOTONCHANNEL),
            "443" => Ok(StatusCode::ERR_USERONCHANNEL),
            "444" => Ok(StatusCode::ERR_NOLOGIN),
            "445" => Ok(StatusCode::ERR_SUMMONDISABLED),
            "446" => Ok(StatusCode::ERR_USERSDISABLED),
            "451" => Ok(StatusCode::ERR_NOTREGISTERED),
            "461" => Ok(StatusCode::ERR_NEEDMOREPARAMS),
            "462" => Ok(StatusCode::ERR_ALREADYREGISTRED),
            "463" => Ok(StatusCode::ERR_NOPERMFORHOST),
            "464" => Ok(StatusCode::ERR_PASSWDMISMATCH),
            "465" => Ok(StatusCode::ERR_YOUREBANNEDCREEP),
            "466" => Ok(StatusCode::ERR_YOUWILLBEBANNED),
            "467" => Ok(StatusCode::ERR_KEYSET),
            "471" => Ok(StatusCode::ERR_CHANNELISFULL),
            "472" => Ok(StatusCode::ERR_UNKNOWNMODE),
            "473" => Ok(StatusCode::ERR_INVITEONLYCHAN),
            "474" => Ok(StatusCode::ERR_BANNEDFROMCHAN),
            "475" => Ok(StatusCode::ERR_BADCHANNELKEY),
            "476" => Ok(StatusCode::ERR_BADCHANMASK),
            "477" => Ok(StatusCode::ERR_NOCHANMODES),
            "478" => Ok(StatusCode::ERR_BANLISTFULL),
            "481" => Ok(StatusCode::ERR_NOPRIVILEGES),
            "482" => Ok(StatusCode::ERR_CHANOPRIVSNEEDED),
            "483" => Ok(StatusCode::ERR_CANTKILLSERVER),
            "484" => Ok(StatusCode::ERR_RESTRICTED),
            "485" => Ok(StatusCode::ERR_UNIQOPPRIVSNEEDED),
            "491" => Ok(StatusCode::ERR_NOOPERHOST),
            "501" => Ok(StatusCode::ERR_UMODEUNKNOWNFLAG),
            "502" => Ok(StatusCode::ERR_USERSDONTMATCH),
            "" => Err("No Status Code in an empty string"),
            _ => Err("Failed to parse status code")
        }
    }
}
